version: "3.8"
name: cubeworld
services:
  server:
    build: .
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "12345:2000/tcp"
    environment:
      - CW_SILENCE=1
      - CW_LAZY=1
      - CW_SEED=26879